version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: iam
    image: mye-iam:v0.1
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
